<?php

use Illuminate\Database\Seeder;
use App\Models\Cliente\Cliente;

class ClientesTableSeeder extends Seeder
{

    public function run()
    {
        $faker = Faker\Factory::create();


$clientes = array(
  array('id' => '4','tipo' => 'Propietario','empresario_id' => '3','empresa_id' => '4'),
  array('id' => '11','tipo' => 'Propietario','empresario_id' => '5','empresa_id' => '9'),
  array('id' => '12','tipo' => 'Propietario','empresario_id' => '4','empresa_id' => '5'),
  array('id' => '13','tipo' => 'Propietario','empresario_id' => '6','empresa_id' => '10'),
  array('id' => '15','tipo' => 'Propietario','empresario_id' => '8','empresa_id' => '12', 'logo' => 'andrely.jpg'),
  array('id' => '16','tipo' => 'Propietario','empresario_id' => '9','empresa_id' => '13'),
  array('id' => '17','tipo' => 'Propietario','empresario_id' => '10','empresa_id' => '15'),
  array('id' => '18','tipo' => 'Propietario','empresario_id' => '11','empresa_id' => '18'),
  array('id' => '19','tipo' => 'Propietario','empresario_id' => '12','empresa_id' => '17'),
  array('id' => '20','tipo' => 'Propietario','empresario_id' => '13','empresa_id' => '14'),
  array('id' => '21','tipo' => 'Propietario','empresario_id' => '14','empresa_id' => '16'),
  array('id' => '22','tipo' => 'Propietario','empresario_id' => '15','empresa_id' => '20'),
  array('id' => '23','tipo' => 'Propietario','empresario_id' => '16','empresa_id' => '21'),
  array('id' => '24','tipo' => 'Propietario','empresario_id' => '17','empresa_id' => '19'),
  array('id' => '25','tipo' => 'Propietario','empresario_id' => '18','empresa_id' => '22'),
  array('id' => '26','tipo' => 'Propietario','empresario_id' => '19','empresa_id' => '23'),
  array('id' => '27','tipo' => 'Propietario','empresario_id' => '20','empresa_id' => '24'),
  array('id' => '28','tipo' => 'Propietario','empresario_id' => '21','empresa_id' => '25'),
  array('id' => '29','tipo' => 'Propietario','empresario_id' => '22','empresa_id' => '26'),
  array('id' => '30','tipo' => 'Propietario','empresario_id' => '23','empresa_id' => '27'),
  array('id' => '31','tipo' => 'Propietario','empresario_id' => '24','empresa_id' => '28'),
  array('id' => '32','tipo' => 'Propietario','empresario_id' => '25','empresa_id' => '29'),
  array('id' => '33','tipo' => 'Propietario','empresario_id' => '26','empresa_id' => '30'),
  array('id' => '34','tipo' => 'Propietario','empresario_id' => '27','empresa_id' => '31'),
  array('id' => '35','tipo' => 'Propietario','empresario_id' => '28','empresa_id' => '33'),
  array('id' => '37','tipo' => 'Propietario','empresario_id' => '30','empresa_id' => '34'),
  array('id' => '38','tipo' => 'Propietario','empresario_id' => '31','empresa_id' => '36'),
  array('id' => '39','tipo' => 'Propietario','empresario_id' => '32','empresa_id' => '35'),
  array('id' => '40','tipo' => 'Propietario','empresario_id' => '33','empresa_id' => '38'),
  array('id' => '41','tipo' => 'Propietario','empresario_id' => '34','empresa_id' => '39'),
  array('id' => '42','tipo' => 'Propietario','empresario_id' => '35','empresa_id' => '40'),
  array('id' => '43','tipo' => 'Propietario','empresario_id' => '36','empresa_id' => '42'),
  array('id' => '44','tipo' => 'Propietario','empresario_id' => '37','empresa_id' => '41'),
  array('id' => '45','tipo' => 'Propietario','empresario_id' => '38','empresa_id' => '43'),
  array('id' => '46','tipo' => 'Propietario','empresario_id' => '39','empresa_id' => '44'),
  array('id' => '47','tipo' => 'Propietario','empresario_id' => '40','empresa_id' => '45'),
  array('id' => '48','tipo' => 'Propietario','empresario_id' => '41','empresa_id' => '46'),
  array('id' => '49','tipo' => 'Propietario','empresario_id' => '42','empresa_id' => '47'),
  array('id' => '50','tipo' => 'Propietario','empresario_id' => '43','empresa_id' => '49'),
  array('id' => '51','tipo' => 'Propietario','empresario_id' => '44','empresa_id' => '48'),
  array('id' => '52','tipo' => 'Propietario','empresario_id' => '45','empresa_id' => '37'),
  array('id' => '53','tipo' => 'Propietario','empresario_id' => '46','empresa_id' => '50'),
  array('id' => '54','tipo' => 'Propietario','empresario_id' => '47','empresa_id' => '51'),
  array('id' => '55','tipo' => 'Propietario','empresario_id' => '48','empresa_id' => '52'),
  array('id' => '56','tipo' => 'Propietario','empresario_id' => '49','empresa_id' => '53'),
  array('id' => '57','tipo' => 'Propietario','empresario_id' => '50','empresa_id' => '54'),
  array('id' => '58','tipo' => 'Propietario','empresario_id' => '51','empresa_id' => '55'),
  array('id' => '59','tipo' => 'Propietario','empresario_id' => '52','empresa_id' => '56'),
  array('id' => '60','tipo' => 'Propietario','empresario_id' => '53','empresa_id' => '57'),
  array('id' => '61','tipo' => 'Propietario','empresario_id' => '54','empresa_id' => '58'),
  array('id' => '62','tipo' => 'Propietario','empresario_id' => '55','empresa_id' => '59'),
  array('id' => '63','tipo' => 'Propietario','empresario_id' => '56','empresa_id' => '60'),
  array('id' => '64','tipo' => 'Propietario','empresario_id' => '57','empresa_id' => '61'),
  array('id' => '65','tipo' => 'Propietario','empresario_id' => '58','empresa_id' => '62'),
  array('id' => '67','tipo' => 'Propietario','empresario_id' => '60','empresa_id' => '64'),
  array('id' => '68','tipo' => 'Propietario','empresario_id' => '61','empresa_id' => '65'),
  array('id' => '69','tipo' => 'Propietario','empresario_id' => '62','empresa_id' => '66'),
  array('id' => '70','tipo' => 'Propietario','empresario_id' => '62','empresa_id' => '67'),
  array('id' => '71','tipo' => 'Propietario','empresario_id' => '63','empresa_id' => '68'),
  array('id' => '72','tipo' => 'Propietario','empresario_id' => '64','empresa_id' => '69'),
  array('id' => '73','tipo' => 'Propietario','empresario_id' => '65','empresa_id' => '70'),
  array('id' => '74','tipo' => 'Propietario','empresario_id' => '66','empresa_id' => '71'),
  array('id' => '75','tipo' => 'Propietario','empresario_id' => '67','empresa_id' => '72'),
  array('id' => '76','tipo' => 'Propietario','empresario_id' => '68','empresa_id' => '73'),
  array('id' => '77','tipo' => 'Propietario','empresario_id' => '69','empresa_id' => '74'),
  array('id' => '78','tipo' => 'Propietario','empresario_id' => '70','empresa_id' => '75'),
  array('id' => '79','tipo' => 'Propietario','empresario_id' => '71','empresa_id' => '76'),
  array('id' => '80','tipo' => 'Propietario','empresario_id' => '72','empresa_id' => '77'),
  array('id' => '81','tipo' => 'Propietario','empresario_id' => '73','empresa_id' => '78'),
  array('id' => '82','tipo' => 'Propietario','empresario_id' => '74','empresa_id' => '79'),
  array('id' => '83','tipo' => 'Propietario','empresario_id' => '75','empresa_id' => '80'),
  array('id' => '84','tipo' => 'Propietario','empresario_id' => '76','empresa_id' => '81'),
  array('id' => '85','tipo' => 'Propietario','empresario_id' => '77','empresa_id' => '82'),
  array('id' => '86','tipo' => 'Propietario','empresario_id' => '78','empresa_id' => '83'),
  array('id' => '87','tipo' => 'Propietario','empresario_id' => '79','empresa_id' => '84'),
  array('id' => '88','tipo' => 'Propietario','empresario_id' => '80','empresa_id' => '85'),
  array('id' => '89','tipo' => 'Propietario','empresario_id' => '81','empresa_id' => '86'),
  array('id' => '90','tipo' => 'Propietario','empresario_id' => '82','empresa_id' => '87'),
  array('id' => '91','tipo' => 'Propietario','empresario_id' => '83','empresa_id' => '88'),
  array('id' => '92','tipo' => 'Propietario','empresario_id' => '84','empresa_id' => '89'),
  array('id' => '93','tipo' => 'Propietario','empresario_id' => '85','empresa_id' => '90'),
  array('id' => '94','tipo' => 'Propietario','empresario_id' => '86','empresa_id' => '91'),
  array('id' => '95','tipo' => 'Propietario','empresario_id' => '87','empresa_id' => '92'),
  array('id' => '96','tipo' => 'Propietario','empresario_id' => '88','empresa_id' => '93'),
  array('id' => '97','tipo' => 'Propietario','empresario_id' => '89','empresa_id' => '94'),
  array('id' => '98','tipo' => 'Propietario','empresario_id' => '90','empresa_id' => '95'),
  array('id' => '99','tipo' => 'Propietario','empresario_id' => '91','empresa_id' => '96'),
  array('id' => '100','tipo' => 'Propietario','empresario_id' => '92','empresa_id' => '97'),
  array('id' => '101','tipo' => 'Propietario','empresario_id' => '93','empresa_id' => '98'),
  array('id' => '102','tipo' => 'Propietario','empresario_id' => '94','empresa_id' => '99'),
  array('id' => '103','tipo' => 'Propietario','empresario_id' => '95','empresa_id' => '100'),
  array('id' => '104','tipo' => 'Propietario','empresario_id' => '96','empresa_id' => '101'),
  array('id' => '105','tipo' => 'Propietario','empresario_id' => '97','empresa_id' => '102'),
  array('id' => '106','tipo' => 'Propietario','empresario_id' => '98','empresa_id' => '103'),
  array('id' => '107','tipo' => 'Propietario','empresario_id' => '99','empresa_id' => '104'),
  array('id' => '108','tipo' => 'Propietario','empresario_id' => '100','empresa_id' => '105'),
  array('id' => '109','tipo' => 'Propietario','empresario_id' => '101','empresa_id' => '106'),
  array('id' => '110','tipo' => 'Propietario','empresario_id' => '102','empresa_id' => '107'),
  array('id' => '111','tipo' => 'Propietario','empresario_id' => '103','empresa_id' => '108'),
  array('id' => '112','tipo' => 'Propietario','empresario_id' => '104','empresa_id' => '109'),
  array('id' => '113','tipo' => 'Propietario','empresario_id' => '105','empresa_id' => '110'),
  array('id' => '114','tipo' => 'Propietario','empresario_id' => '106','empresa_id' => '111'),
  array('id' => '115','tipo' => 'Propietario','empresario_id' => '107','empresa_id' => '112'),
  array('id' => '116','tipo' => 'Propietario','empresario_id' => '108','empresa_id' => '113'),
  array('id' => '117','tipo' => 'Propietario','empresario_id' => '59','empresa_id' => '115'),
  array('id' => '118','tipo' => 'Propietario','empresario_id' => '109','empresa_id' => '116'),
  array('id' => '119','tipo' => 'Propietario','empresario_id' => '110','empresa_id' => '117'),
  array('id' => '120','tipo' => 'Propietario','empresario_id' => '29','empresa_id' => '114'),
  array('id' => '122','tipo' => 'Propietario','empresario_id' => '111','empresa_id' => '119'),
  array('id' => '123','tipo' => 'Propietario','empresario_id' => '112','empresa_id' => '120'),
  array('id' => '124','tipo' => 'Propietario','empresario_id' => '113','empresa_id' => '121'),
  array('id' => '125','tipo' => 'Propietario','empresario_id' => '114','empresa_id' => '122'),
  array('id' => '126','tipo' => 'Propietario','empresario_id' => '115','empresa_id' => '123'),
  array('id' => '128','tipo' => 'Propietario','empresario_id' => '117','empresa_id' => '125'),
  array('id' => '129','tipo' => 'Propietario','empresario_id' => '118','empresa_id' => '126'),
  array('id' => '130','tipo' => 'Propietario','empresario_id' => '119','empresa_id' => '127'),
  array('id' => '131','tipo' => 'Propietario','empresario_id' => '120','empresa_id' => '128'),
  array('id' => '132','tipo' => 'Propietario','empresario_id' => '121','empresa_id' => '129'),
  array('id' => '133','tipo' => 'Propietario','empresario_id' => '122','empresa_id' => '130'),
  array('id' => '134','tipo' => 'Propietario','empresario_id' => '123','empresa_id' => '131'),
  array('id' => '135','tipo' => 'Propietario','empresario_id' => '124','empresa_id' => '132'),
  array('id' => '136','tipo' => 'Propietario','empresario_id' => '125','empresa_id' => '133'),
  array('id' => '137','tipo' => 'Propietario','empresario_id' => '126','empresa_id' => '134'),
  array('id' => '138','tipo' => 'Propietario','empresario_id' => '127','empresa_id' => '135'),
  array('id' => '139','tipo' => 'Propietario','empresario_id' => '128','empresa_id' => '136'),
  array('id' => '140','tipo' => 'Propietario','empresario_id' => '129','empresa_id' => '137'),
  array('id' => '141','tipo' => 'Propietario','empresario_id' => '130','empresa_id' => '138'),
  array('id' => '142','tipo' => 'Propietario','empresario_id' => '131','empresa_id' => '139'),
  array('id' => '143','tipo' => 'Propietario','empresario_id' => '132','empresa_id' => '140'),
  array('id' => '144','tipo' => 'Propietario','empresario_id' => '133','empresa_id' => '141'),
  array('id' => '145','tipo' => 'Propietario','empresario_id' => '134','empresa_id' => '142'),
  array('id' => '146','tipo' => 'Propietario','empresario_id' => '135','empresa_id' => '143'),
  array('id' => '147','tipo' => 'Propietario','empresario_id' => '136','empresa_id' => '144'),
  array('id' => '148','tipo' => 'Propietario','empresario_id' => '137','empresa_id' => '145'),
  array('id' => '149','tipo' => 'Propietario','empresario_id' => '138','empresa_id' => '146'),
  array('id' => '150','tipo' => 'Propietario','empresario_id' => '139','empresa_id' => '147'),
  array('id' => '151','tipo' => 'Propietario','empresario_id' => '140','empresa_id' => '148'),
  array('id' => '152','tipo' => 'Propietario','empresario_id' => '141','empresa_id' => '149'),
  array('id' => '153','tipo' => 'Propietario','empresario_id' => '142','empresa_id' => '150'),
  array('id' => '154','tipo' => 'Propietario','empresario_id' => '143','empresa_id' => '151'),
  array('id' => '155','tipo' => 'Propietario','empresario_id' => '144','empresa_id' => '152'),
  array('id' => '156','tipo' => 'Propietario','empresario_id' => '145','empresa_id' => '154'),
  array('id' => '157','tipo' => 'Propietario','empresario_id' => '146','empresa_id' => '155'),
  array('id' => '158','tipo' => 'Propietario','empresario_id' => '147','empresa_id' => '156'),
  array('id' => '159','tipo' => 'Propietario','empresario_id' => '148','empresa_id' => '157'),
  array('id' => '160','tipo' => 'Propietario','empresario_id' => '7','empresa_id' => '153'),
  array('id' => '161','tipo' => 'Propietario','empresario_id' => '149','empresa_id' => '158'),
  array('id' => '162','tipo' => 'Propietario','empresario_id' => '150','empresa_id' => '159'),
  array('id' => '163','tipo' => 'Propietario','empresario_id' => '151','empresa_id' => '160'),
  array('id' => '164','tipo' => 'Propietario','empresario_id' => '152','empresa_id' => '161'),
  array('id' => '165','tipo' => 'Propietario','empresario_id' => '153','empresa_id' => '162'),
  array('id' => '166','tipo' => 'Propietario','empresario_id' => '154','empresa_id' => '163'),
  array('id' => '167','tipo' => 'Propietario','empresario_id' => '155','empresa_id' => '164'),
  array('id' => '168','tipo' => 'Propietario','empresario_id' => '156','empresa_id' => '165'),
  array('id' => '169','tipo' => 'Propietario','empresario_id' => '157','empresa_id' => '166'),
  array('id' => '170','tipo' => 'Representante','empresario_id' => '158','empresa_id' => '167'),
  array('id' => '172','tipo' => 'Propietario','empresario_id' => '160','empresa_id' => '169'),
  array('id' => '173','tipo' => 'Propietario','empresario_id' => '161','empresa_id' => '170'),
  array('id' => '174','tipo' => 'Propietario','empresario_id' => '162','empresa_id' => '171'),
  array('id' => '175','tipo' => 'Propietario','empresario_id' => '163','empresa_id' => '172'),
  array('id' => '176','tipo' => 'Propietario','empresario_id' => '164','empresa_id' => '173'),
  array('id' => '177','tipo' => 'Propietario','empresario_id' => '165','empresa_id' => '174'),
  array('id' => '178','tipo' => 'Propietario','empresario_id' => '166','empresa_id' => '175'),
  array('id' => '180','tipo' => 'Propietario','empresario_id' => '167','empresa_id' => '177'),
  array('id' => '181','tipo' => 'Propietario','empresario_id' => '168','empresa_id' => '178'),
  array('id' => '182','tipo' => 'Propietario','empresario_id' => '169','empresa_id' => '179'),
  array('id' => '183','tipo' => 'Propietario','empresario_id' => '170','empresa_id' => '180'),
  array('id' => '184','tipo' => 'Propietario','empresario_id' => '171','empresa_id' => '181'),
  array('id' => '185','tipo' => 'Propietario','empresario_id' => '172','empresa_id' => '182'),
  array('id' => '186','tipo' => 'Propietario','empresario_id' => '174','empresa_id' => '183'),
  array('id' => '187','tipo' => 'Propietario','empresario_id' => '175','empresa_id' => '184'),
  array('id' => '188','tipo' => 'Propietario','empresario_id' => '176','empresa_id' => '185'),
  array('id' => '189','tipo' => 'Propietario','empresario_id' => '177','empresa_id' => '186'),
  array('id' => '190','tipo' => 'Propietario','empresario_id' => '178','empresa_id' => '187'),
  array('id' => '191','tipo' => 'Propietario','empresario_id' => '179','empresa_id' => '188'),
  array('id' => '192','tipo' => 'Propietario','empresario_id' => '180','empresa_id' => '189'),
  array('id' => '193','tipo' => 'Propietario','empresario_id' => '181','empresa_id' => '190'),
  array('id' => '194','tipo' => 'Propietario','empresario_id' => '182','empresa_id' => '191'),
  array('id' => '195','tipo' => 'Propietario','empresario_id' => '183','empresa_id' => '192'),
  array('id' => '196','tipo' => 'Propietario','empresario_id' => '184','empresa_id' => '193'),
  array('id' => '197','tipo' => 'Propietario','empresario_id' => '185','empresa_id' => '194'),
  array('id' => '198','tipo' => 'Propietario','empresario_id' => '186','empresa_id' => '195'),
  array('id' => '199','tipo' => 'Propietario','empresario_id' => '187','empresa_id' => '196'),
  array('id' => '200','tipo' => 'Propietario','empresario_id' => '188','empresa_id' => '197'),
  array('id' => '201','tipo' => 'Propietario','empresario_id' => '189','empresa_id' => '198'),
  array('id' => '202','tipo' => 'Propietario','empresario_id' => '190','empresa_id' => '199'),
  array('id' => '203','tipo' => 'Propietario','empresario_id' => '191','empresa_id' => '200'),
  array('id' => '204','tipo' => 'Propietario','empresario_id' => '192','empresa_id' => '201'),
  array('id' => '205','tipo' => 'Propietario','empresario_id' => '193','empresa_id' => '202'),
  array('id' => '206','tipo' => 'Propietario','empresario_id' => '194','empresa_id' => '203'),
  array('id' => '207','tipo' => 'Propietario','empresario_id' => '195','empresa_id' => '204'),
  array('id' => '208','tipo' => 'Propietario','empresario_id' => '196','empresa_id' => '205'),
  array('id' => '209','tipo' => 'Propietario','empresario_id' => '197','empresa_id' => '206'),
  array('id' => '210','tipo' => 'Propietario','empresario_id' => '198','empresa_id' => '207'),
  array('id' => '211','tipo' => 'Propietario','empresario_id' => '199','empresa_id' => '208'),
  array('id' => '212','tipo' => 'Propietario','empresario_id' => '196','empresa_id' => '209'),
  array('id' => '213','tipo' => 'Propietario','empresario_id' => '200','empresa_id' => '210'),
  array('id' => '214','tipo' => 'Propietario','empresario_id' => '201','empresa_id' => '211'),
  array('id' => '215','tipo' => 'Propietario','empresario_id' => '202','empresa_id' => '212'),
  array('id' => '216','tipo' => 'Propietario','empresario_id' => '203','empresa_id' => '213'),
  array('id' => '217','tipo' => 'Propietario','empresario_id' => '204','empresa_id' => '214'),
  array('id' => '218','tipo' => 'Propietario','empresario_id' => '205','empresa_id' => '215'),
  array('id' => '219','tipo' => 'Propietario','empresario_id' => '206','empresa_id' => '216'),
  array('id' => '220','tipo' => 'Propietario','empresario_id' => '207','empresa_id' => '217'),
  array('id' => '221','tipo' => 'Propietario','empresario_id' => '208','empresa_id' => '218'),
  array('id' => '222','tipo' => 'Propietario','empresario_id' => '209','empresa_id' => '219'),
  array('id' => '223','tipo' => 'Representante','empresario_id' => '210','empresa_id' => '220'),
  array('id' => '224','tipo' => 'Propietario','empresario_id' => '211','empresa_id' => '221'),
  array('id' => '225','tipo' => 'Propietario','empresario_id' => '212','empresa_id' => '222'),
  array('id' => '226','tipo' => 'Propietario','empresario_id' => '213','empresa_id' => '223'),
  array('id' => '227','tipo' => 'Propietario','empresario_id' => '214','empresa_id' => '224'),
  array('id' => '228','tipo' => 'Propietario','empresario_id' => '215','empresa_id' => '225'),
  array('id' => '229','tipo' => 'Propietario','empresario_id' => '216','empresa_id' => '226'),
  array('id' => '230','tipo' => 'Propietario','empresario_id' => '217','empresa_id' => '227'),
  array('id' => '231','tipo' => 'Propietario','empresario_id' => '218','empresa_id' => '228'),
  array('id' => '232','tipo' => 'Propietario','empresario_id' => '219','empresa_id' => '229'),
  array('id' => '233','tipo' => 'Propietario','empresario_id' => '220','empresa_id' => '230'),
  array('id' => '234','tipo' => 'Propietario','empresario_id' => '221','empresa_id' => '231'),
  array('id' => '235','tipo' => 'Propietario','empresario_id' => '222','empresa_id' => '232'),
  array('id' => '236','tipo' => 'Propietario','empresario_id' => '223','empresa_id' => '233'),
  array('id' => '237','tipo' => 'Propietario','empresario_id' => '224','empresa_id' => '234'),
  array('id' => '238','tipo' => 'Propietario','empresario_id' => '225','empresa_id' => '235'),
  array('id' => '239','tipo' => 'Propietario','empresario_id' => '226','empresa_id' => '236'),
  array('id' => '240','tipo' => 'Propietario','empresario_id' => '227','empresa_id' => '237'),
  array('id' => '241','tipo' => 'Propietario','empresario_id' => '228','empresa_id' => '238'),
  array('id' => '242','tipo' => 'Propietario','empresario_id' => '229','empresa_id' => '239'),
  array('id' => '243','tipo' => 'Propietario','empresario_id' => '230','empresa_id' => '240'),
  array('id' => '244','tipo' => 'Propietario','empresario_id' => '231','empresa_id' => '241'),
  array('id' => '245','tipo' => 'Propietario','empresario_id' => '232','empresa_id' => '242'),
  array('id' => '246','tipo' => 'Propietario','empresario_id' => '125','empresa_id' => '243'),
  array('id' => '247','tipo' => 'Propietario','empresario_id' => '233','empresa_id' => '244'),
  array('id' => '248','tipo' => 'Propietario','empresario_id' => '234','empresa_id' => '245'),
  array('id' => '249','tipo' => 'Propietario','empresario_id' => '235','empresa_id' => '246'),
  array('id' => '250','tipo' => 'Propietario','empresario_id' => '236','empresa_id' => '247'),
  array('id' => '251','tipo' => 'Propietario','empresario_id' => '237','empresa_id' => '248', 'logo' => 'milagrosa.jpg'),
  array('id' => '252','tipo' => 'Propietario','empresario_id' => '182','empresa_id' => '249'),
  array('id' => '253','tipo' => 'Propietario','empresario_id' => '238','empresa_id' => '250'),
  array('id' => '254','tipo' => 'Propietario','empresario_id' => '239','empresa_id' => '251'),
  array('id' => '255','tipo' => 'Propietario','empresario_id' => '51','empresa_id' => '252'),
  array('id' => '256','tipo' => 'Propietario','empresario_id' => '241','empresa_id' => '254'),
  array('id' => '257','tipo' => 'Propietario','empresario_id' => '242','empresa_id' => '255'),
  array('id' => '258','tipo' => 'Propietario','empresario_id' => '243','empresa_id' => '256'),
  array('id' => '259','tipo' => 'Propietario','empresario_id' => '244','empresa_id' => '257'),
  array('id' => '260','tipo' => 'Propietario','empresario_id' => '245','empresa_id' => '258'),
  array('id' => '261','tipo' => 'Propietario','empresario_id' => '246','empresa_id' => '259'),
  array('id' => '262','tipo' => 'Propietario','empresario_id' => '247','empresa_id' => '260'),
  array('id' => '263','tipo' => 'Propietario','empresario_id' => '248','empresa_id' => '261'),
  array('id' => '264','tipo' => 'Propietario','empresario_id' => '249','empresa_id' => '262'),
  array('id' => '265','tipo' => 'Propietario','empresario_id' => '250','empresa_id' => '263'),
  array('id' => '266','tipo' => 'Propietario','empresario_id' => '251','empresa_id' => '264'),
  array('id' => '267','tipo' => 'Propietario','empresario_id' => '252','empresa_id' => '265'),
  array('id' => '268','tipo' => 'Propietario','empresario_id' => '253','empresa_id' => '266'),
  array('id' => '269','tipo' => 'Propietario','empresario_id' => '254','empresa_id' => '268'),
  array('id' => '270','tipo' => 'Propietario','empresario_id' => '255','empresa_id' => '269'),
  array('id' => '271','tipo' => 'Propietario','empresario_id' => '256','empresa_id' => '271'),
  array('id' => '272','tipo' => 'Propietario','empresario_id' => '257','empresa_id' => '272'),
  array('id' => '273','tipo' => 'Propietario','empresario_id' => '258','empresa_id' => '273'),
  array('id' => '274','tipo' => 'Propietario','empresario_id' => '259','empresa_id' => '274'),
  array('id' => '275','tipo' => 'Propietario','empresario_id' => '260','empresa_id' => '275'),
  array('id' => '276','tipo' => 'Propietario','empresario_id' => '261','empresa_id' => '276'),
  array('id' => '277','tipo' => 'Propietario','empresario_id' => '262','empresa_id' => '277'),
  // array('id' => '278','tipo' => 'Propietario','empresario_id' => '263','empresa_id' => '275'),
  // array('id' => '279','tipo' => 'Propietario','empresario_id' => '264','empresa_id' => '275'),
  // array('id' => '280','tipo' => 'Propietario','empresario_id' => '265','empresa_id' => '275'),
  // array('id' => '281','tipo' => 'Propietario','empresario_id' => '266','empresa_id' => '127'),
  // array('id' => '282','tipo' => 'Propietario','empresario_id' => '267','empresa_id' => '277'),
  // array('id' => '283','tipo' => 'Propietario','empresario_id' => '268','empresa_id' => '127'),
  array('id' => '284','tipo' => 'Propietario','empresario_id' => '269','empresa_id' => '278'),
  // array('id' => '285','tipo' => 'Representante','empresario_id' => '270','empresa_id' => '278'),
  array('id' => '286','tipo' => 'Propietario','empresario_id' => '272','empresa_id' => '279'),
  array('id' => '287','tipo' => 'Propietario','empresario_id' => '271','empresa_id' => '280'),
  array('id' => '288','tipo' => 'Propietario','empresario_id' => '273','empresa_id' => '283'),
  array('id' => '289','tipo' => 'Propietario','empresario_id' => '274','empresa_id' => '284'),
  array('id' => '290','tipo' => 'Propietario','empresario_id' => '275','empresa_id' => '285'),
  array('id' => '291','tipo' => 'Propietario','empresario_id' => '277','empresa_id' => '286'),
  array('id' => '292','tipo' => 'Propietario','empresario_id' => '278','empresa_id' => '287'),
  array('id' => '293','tipo' => 'Propietario','empresario_id' => '279','empresa_id' => '289'),
  array('id' => '294','tipo' => 'Propietario','empresario_id' => '280','empresa_id' => '290'),
  array('id' => '295','tipo' => 'Propietario','empresario_id' => '284','empresa_id' => '295'),
  array('id' => '296','tipo' => 'Propietario','empresario_id' => '240','empresa_id' => '253'),
  array('id' => '297','tipo' => 'Propietario','empresario_id' => '285','empresa_id' => '296'),
  array('id' => '298','tipo' => 'Propietario','empresario_id' => '286','empresa_id' => '297'),
  array('id' => '299','tipo' => 'Propietario','empresario_id' => '287','empresa_id' => '298'),
  array('id' => '300','tipo' => 'Propietario','empresario_id' => '288','empresa_id' => '300'),
  array('id' => '301','tipo' => 'Propietario','empresario_id' => '293','empresa_id' => '301'),
  // array('id' => '302','tipo' => 'Representante','empresario_id' => '298','empresa_id' => '181'),
  // array('id' => '303','tipo' => 'Propietario','empresario_id' => '299','empresa_id' => '91'),
  // array('id' => '304','tipo' => 'Propietario','empresario_id' => '299','empresa_id' => '91'),
  array('id' => '305','tipo' => 'Propietario','empresario_id' => '289','empresa_id' => '304'),
  array('id' => '306','tipo' => 'Propietario','empresario_id' => '300','empresa_id' => '306'),
  // array('id' => '307','tipo' => 'Propietario','empresario_id' => '300','empresa_id' => '306'),
  array('id' => '308','tipo' => 'Propietario','empresario_id' => '301','empresa_id' => '307'),
  array('id' => '309','tipo' => 'Propietario','empresario_id' => '302','empresa_id' => '308'),
  // array('id' => '310','tipo' => 'Propietario','empresario_id' => '303','empresa_id' => '219'),
  array('id' => '311','tipo' => 'Propietario','empresario_id' => '304','empresa_id' => '309'),
  array('id' => '312','tipo' => 'Propietario','empresario_id' => '305','empresa_id' => '310'),
  // array('id' => '313','tipo' => 'Propietario','empresario_id' => '306','empresa_id' => '219'),
  array('id' => '314','tipo' => 'Propietario','empresario_id' => '307','empresa_id' => '311'),
  array('id' => '315','tipo' => 'Propietario','empresario_id' => '159','empresa_id' => '168'),
  array('id' => '316','tipo' => 'Propietario','empresario_id' => '308','empresa_id' => '313'),
  // array('id' => '317','tipo' => 'Propietario','empresario_id' => '309','empresa_id' => '69'),
  array('id' => '318','tipo' => 'Propietario','empresario_id' => '310','empresa_id' => '314'),
  array('id' => '319','tipo' => 'Propietario','empresario_id' => '311','empresa_id' => '315'),
  array('id' => '320','tipo' => 'Propietario','empresario_id' => '296','empresa_id' => '316'),
  array('id' => '321','tipo' => 'Propietario','empresario_id' => '312','empresa_id' => '318'),
  array('id' => '322','tipo' => 'Propietario','empresario_id' => '313','empresa_id' => '319'),
  // array('id' => '323','tipo' => 'Propietario','empresario_id' => '68','empresa_id' => '73'),
  array('id' => '324','tipo' => 'Propietario','empresario_id' => '314','empresa_id' => '320'),
  array('id' => '325','tipo' => 'Propietario','empresario_id' => '116','empresa_id' => '124'),
  // array('id' => '326','tipo' => 'Propietario','empresario_id' => '315','empresa_id' => '123'),
  array('id' => '327','tipo' => 'Propietario','empresario_id' => '316','empresa_id' => '321'),
  array('id' => '328','tipo' => 'Propietario','empresario_id' => '322','empresa_id' => '328'),
  array('id' => '329','tipo' => 'Propietario','empresario_id' => '323','empresa_id' => '329'),
  array('id' => '330','tipo' => 'Propietario','empresario_id' => '324','empresa_id' => '330'),
  array('id' => '331','tipo' => 'Propietario','empresario_id' => '321','empresa_id' => '327'),
  // array('id' => '332','tipo' => 'Representante','empresario_id' => '281','empresa_id' => '89'),
  // array('id' => '333','tipo' => 'Representante','empresario_id' => '251','empresa_id' => '13'),
  array('id' => '334','tipo' => 'Propietario','empresario_id' => '325','empresa_id' => '333'),
  array('id' => '335','tipo' => 'Representante','empresario_id' => '251','empresa_id' => '331'),
  array('id' => '336','tipo' => 'Propietario','empresario_id' => '326','empresa_id' => '332'),
  array('id' => '337','tipo' => 'Propietario','empresario_id' => '327','empresa_id' => '334'),
  // array('id' => '338','tipo' => 'Representante','empresario_id' => '316','empresa_id' => '321'),
  array('id' => '339','tipo' => 'Propietario','empresario_id' => '328','empresa_id' => '335'),
  // array('id' => '340','tipo' => 'Propietario','empresario_id' => '328','empresa_id' => '335'),
  array('id' => '341','tipo' => 'Propietario','empresario_id' => '329','empresa_id' => '336'),
  array('id' => '342','tipo' => 'Propietario','empresario_id' => '330','empresa_id' => '337'),
  array('id' => '343','tipo' => 'Propietario','empresario_id' => '332','empresa_id' => '340'),
  array('id' => '344','tipo' => 'Propietario','empresario_id' => '331','empresa_id' => '338'),
  array('id' => '345','tipo' => 'Representante','empresario_id' => '333','empresa_id' => '341'),
  array('id' => '346','tipo' => 'Propietario','empresario_id' => '334','empresa_id' => '342'),
  array('id' => '347','tipo' => 'Propietario','empresario_id' => '335','empresa_id' => '343'),
  array('id' => '349','tipo' => 'Propietario','empresario_id' => '336','empresa_id' => '344'),
  array('id' => '350','tipo' => 'Propietario','empresario_id' => '337','empresa_id' => '345'),
  array('id' => '351','tipo' => 'Propietario','empresario_id' => '338','empresa_id' => '346'),
  array('id' => '352','tipo' => 'Propietario','empresario_id' => '339','empresa_id' => '347'),
  array('id' => '353','tipo' => 'Propietario','empresario_id' => '340','empresa_id' => '348'),
  array('id' => '354','tipo' => 'Propietario','empresario_id' => '341','empresa_id' => '349'),
  array('id' => '355','tipo' => 'Propietario','empresario_id' => '342','empresa_id' => '350'),
  array('id' => '356','tipo' => 'Propietario','empresario_id' => '343','empresa_id' => '351'),
  array('id' => '357','tipo' => 'Propietario','empresario_id' => '344','empresa_id' => '352'),
  array('id' => '358','tipo' => 'Propietario','empresario_id' => '345','empresa_id' => '353'),
  array('id' => '359','tipo' => 'Propietario','empresario_id' => '319','empresa_id' => '325'),
  array('id' => '360','tipo' => 'Propietario','empresario_id' => '346','empresa_id' => '355'),
  array('id' => '361','tipo' => 'Propietario','empresario_id' => '347','empresa_id' => '356'),
  array('id' => '362','tipo' => 'Propietario','empresario_id' => '348','empresa_id' => '357'),
  array('id' => '363','tipo' => 'Propietario','empresario_id' => '349','empresa_id' => '358'),
  // array('id' => '364','tipo' => 'Propietario','empresario_id' => '349','empresa_id' => '358'),
  array('id' => '365','tipo' => 'Propietario','empresario_id' => '350','empresa_id' => '359'),
  array('id' => '366','tipo' => 'Propietario','empresario_id' => '351','empresa_id' => '360'),
  array('id' => '367','tipo' => 'Propietario','empresario_id' => '352','empresa_id' => '361'),
  array('id' => '368','tipo' => 'Propietario','empresario_id' => '353','empresa_id' => '362'),
  array('id' => '369','tipo' => 'Propietario','empresario_id' => '354','empresa_id' => '363'),
  array('id' => '370','tipo' => 'Propietario','empresario_id' => '355','empresa_id' => '364'),
  array('id' => '371','tipo' => 'Propietario','empresario_id' => '356','empresa_id' => '365'),
  array('id' => '372','tipo' => 'Propietario','empresario_id' => '357','empresa_id' => '366'),
  array('id' => '373','tipo' => 'Propietario','empresario_id' => '358','empresa_id' => '367'),
  array('id' => '374','tipo' => 'Propietario','empresario_id' => '360','empresa_id' => '368'),
  array('id' => '375','tipo' => 'Propietario','empresario_id' => '359','empresa_id' => '369'),
  array('id' => '376','tipo' => 'Propietario','empresario_id' => '361','empresa_id' => '370'),
  array('id' => '377','tipo' => 'Propietario','empresario_id' => '362','empresa_id' => '371'),
  array('id' => '378','tipo' => 'Propietario','empresario_id' => '363','empresa_id' => '372'),
  array('id' => '379','tipo' => 'Propietario','empresario_id' => '364','empresa_id' => '375'),
  array('id' => '380','tipo' => 'Propietario','empresario_id' => '365','empresa_id' => '376'),
  // array('id' => '381','tipo' => 'Representante','empresario_id' => '365','empresa_id' => '376'),
  array('id' => '382','tipo' => 'Propietario','empresario_id' => '366','empresa_id' => '373'),
  array('id' => '383','tipo' => 'Propietario','empresario_id' => '367','empresa_id' => '377'),
  array('id' => '384','tipo' => 'Propietario','empresario_id' => '368','empresa_id' => '378'),
  array('id' => '385','tipo' => 'Propietario','empresario_id' => '369','empresa_id' => '379'),
  array('id' => '386','tipo' => 'Propietario','empresario_id' => '370','empresa_id' => '380'),
  array('id' => '387','tipo' => 'Propietario','empresario_id' => '371','empresa_id' => '381'),
  // array('id' => '388','tipo' => 'Representante','empresario_id' => '372','empresa_id' => '5'),
  array('id' => '389','tipo' => 'Propietario','empresario_id' => '373','empresa_id' => '383'),
  array('id' => '390','tipo' => 'Propietario','empresario_id' => '374','empresa_id' => '384'),
  // array('id' => '391','tipo' => 'Representante','empresario_id' => '76','empresa_id' => '384'),
  // array('id' => '392','tipo' => 'Representante','empresario_id' => '81','empresa_id' => '384'),
  array('id' => '393','tipo' => 'Propietario','empresario_id' => '376','empresa_id' => '386'),
  array('id' => '394','tipo' => 'Propietario','empresario_id' => '375','empresa_id' => '385'),
  array('id' => '395','tipo' => 'Propietario','empresario_id' => '377','empresa_id' => '387'),
  array('id' => '396','tipo' => 'Propietario','empresario_id' => '378','empresa_id' => '388'),
  // array('id' => '397','tipo' => 'Representante','empresario_id' => '350','empresa_id' => '388'),
  array('id' => '398','tipo' => 'Propietario','empresario_id' => '379','empresa_id' => '389'),
  array('id' => '399','tipo' => 'Propietario','empresario_id' => '380','empresa_id' => '390'),
  array('id' => '400','tipo' => 'Propietario','empresario_id' => '381','empresa_id' => '391'),
  array('id' => '401','tipo' => 'Propietario','empresario_id' => '382','empresa_id' => '392'),
  array('id' => '402','tipo' => 'Propietario','empresario_id' => '383','empresa_id' => '393'),
  array('id' => '403','tipo' => 'Propietario','empresario_id' => '384','empresa_id' => '394'),
  array('id' => '404','tipo' => 'Propietario','empresario_id' => '385','empresa_id' => '395'),
  // array('id' => '405','tipo' => 'Propietario','empresario_id' => '385','empresa_id' => '395'),
  // array('id' => '406','tipo' => 'Representante','empresario_id' => '260','empresa_id' => '275'')
);


        for ($i = 0; $i < count($clientes); $i++) { 
            $table = new Cliente;
            $table->id              = $clientes[$i]['id'];
            $table->tipo            = $clientes[$i]['tipo'];
            $table->empresa_id      = $clientes[$i]['empresa_id'];
            $table->empresario_id   = $clientes[$i]['empresario_id'];
            // $table->procedencia
            // $table->estado
            // $table->logo
            $table->save();

        }

            // for($i = 1; $i <= 20 ; $i++)
            // {
            //     $table = new Cliente;
            //     $table->empresario_id   = $faker->numberBetween(1,15);
            //     $table->empresa_id      = $faker->numberBetween(1,15);
            //     $table->procedencia     = $faker->numberBetween(1,4);
            //     $table->tipo            = $faker->numberBetween(1,2);

            //     $table->cdmype_id       = 1;
                
            //     $table->save();

            // }
            
    }
}
